# ADetailer 2CN Plus Configuration
# This file contains all configuration options for the face detection pipeline
# Integrated with existing portrait-enhancer pipeline

# Pipeline configuration
pipeline:
  # Face detector configurations
  detectors:
    - name: blazeface
      confidence_threshold: 0.5
      nms_threshold: 0.3
      max_faces: 100
      input_size: 128
      model_path: null  # Will use default model
    
    - name: retinaface
      confidence_threshold: 0.7
      nms_threshold: 0.3
      max_faces: 50
      input_size: 640
      model_path: null  # Will use default model
    
    - name: mtcnn
      confidence_threshold: 0.6
      nms_threshold: 0.3
      max_faces: 100
      min_face_size: 20
      factor: 0.709
      thresholds: [0.6, 0.7, 0.7]
  
  # Search strategy configuration
  search:
    strategy: sliding_window  # Options: sliding_window, multi_scale
    window_size: 512
    stride: 256
    scale_factors: [1.0, 0.75, 0.5, 0.25]
  
  # Cascade detection settings
  enable_cascade: true
  cascade_order: [blazeface, retinaface, mtcnn]

# A-Pass pipeline configuration (integrated with portrait-enhancer)
a_pass:
  enabled: true
  model_path: null  # Path to A-Pass model (optional)
  batch_size: 4
  device: auto  # Options: auto, cpu, cuda
  workdir: "work"  # Working directory for A-Pass processing

# B-Pass pipeline configuration (integrated with portrait-enhancer)
b_pass:
  enabled: true
  model_path: null  # Path to B-Pass model (optional)
  batch_size: 4
  device: auto  # Options: auto, cpu, cuda
  workdir: "work"  # Working directory for B-Pass processing
  output_dir: "output"  # Output directory for final results
  config_path: "config.yaml"  # Path to portrait-enhancer config

# Input/Output settings
input_dir: null  # Input directory for batch processing
output_dir: null  # Output directory for results

# Performance settings
num_workers: 4
use_gpu: true
gpu_memory_fraction: 0.8

# Logging configuration
log_level: INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_file: null  # Log file path (optional)

# A1111 integration settings (for B-Pass)
a1111_base_url: "http://127.0.0.1:7860"  # A1111 base URL
a1111_api_key: null   # A1111 API key (optional)

# Portrait-enhancer integration settings
portrait_enhancer:
  enabled: true
  auto_detect: true  # Auto-detect portrait-enhancer installation
  path: "../portrait-enhancer"  # Path to portrait-enhancer directory
  use_existing_config: true  # Use existing portrait-enhancer config
  fallback_to_basic: true  # Fallback to basic enhancement if portrait-enhancer fails
