# ADetailer 2CN Plus - Enhanced Configuration
pipeline:
  detectors:
    - name: mediapipe
      confidence_threshold: 0.7
      detection_confidence: 0.7
      model_selection: 0
      with_landmarks: true
      max_faces: 5
    - name: opencv
      confidence_threshold: 0.3
      max_faces: 5
      scale_factor: 1.05
      min_neighbors: 3
  enable_fallback: true
  min_faces_threshold: 1

# A1111 Integration
a1111_base_url: "http://127.0.0.1:7860"

# Performance
use_gpu: true
num_workers: 4

# Paths
input_dir: "data/samples"
output_dir: "output"

# Logging
log_level: INFO

# Facial Enhancement System
facial_enhancement:
  # Contouring and makeup application
  contouring:
    enabled: true
    intensity: 1.5  # Overall contouring intensity (0.0 - 1.0) - ПІДВИЩЕНО
    blend_strength: 0.8  # How strongly to blend with original (0.0 - 1.0) - ПІДВИЩЕНО
    
  # Expression lines and aging
  expression_lines:
    enabled: true
    neutral_intensity: 0.3  # Intensity for neutral expressions (0.0 - 1.0)
    smile_intensity: 0.6  # Intensity for smiling expressions (0.0 - 1.0)
    
  # Person-specific settings
  person_profiles:
    massy:
      contour_strength: 1.2  # Stronger contouring for Massy - ПІДВИЩЕНО
      expression_strength: 0.8  # ПІДВИЩЕНО
      lip_enhancement:
        cupids_bow_intensity: 1.2  # Cupid's bow definition - ПІДВИЩЕНО
        lip_volume_boost: 1.0  # Lower lip volume enhancement - ПІДВИЩЕНО
        corner_definition: 0.8  # Lip corner shadows - ПІДВИЩЕНО
        perioral_wrinkles: 0.8  # Wrinkles around mouth area - ПІДВИЩЕНО
        color_intensity: 1.5  # Lip color enhancement - ПІДВИЩЕНО
    orbi:
      contour_strength: 1.0  # Moderate contouring for Orbi - ПІДВИЩЕНО
      expression_strength: 0.8  # ПІДВИЩЕНО
      lip_enhancement:
        cupids_bow_intensity: 1.0  # Subtle Cupid's bow - ПІДВИЩЕНО
        lip_volume_boost: 0.8  # Moderate lip volume - ПІДВИЩЕНО
        corner_definition: 0.7  # Light corner shadows - ПІДВИЩЕНО
        perioral_wrinkles: 0.6  # Minimal perioral lines - ПІДВИЩЕНО
        color_intensity: 1.2  # Natural lip color - ПІДВИЩЕНО
    yana:
      contour_strength: 1.1  # Balanced contouring for Yana - ПІДВИЩЕНО
      expression_strength: 0.75  # ПІДВИЩЕНО
      lip_enhancement:
        cupids_bow_intensity: 1.1  # Balanced Cupid's bow - ПІДВИЩЕНО
        lip_volume_boost: 0.8  # Natural lip volume - ПІДВИЩЕНО
        corner_definition: 0.7  # Moderate corner definition - ПІДВИЩЕНО
        perioral_wrinkles: 0.7  # Light perioral wrinkles - ПІДВИЩЕНО
        color_intensity: 1.3  # Enhanced but natural lip color - ПІДВИЩЕНО