services:
  portrait-enhancer:
    build: .
    ports:
      - "7860:7860"
    volumes:
      - ./portrait-enhancer/input:/workspace/portrait-enhancer/input
      - ./portrait-enhancer/output:/workspace/portrait-enhancer/output
      - ./portrait-enhancer/work:/workspace/portrait-enhancer/work
      - ./models:/workspace/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
