# Models Configuration
# Configuration for Stable Diffusion and ControlNet models

# Stable Diffusion models
stable_diffusion:
  default_model: "realistic_vision_v5.1.safetensors"
  models:
    - name: "realistic_vision_v5.1.safetensors"
      type: "checkpoint"
      description: "Realistic Vision v5.1 - High quality realistic portraits"
      source: "civitai"
      url: "https://civitai.com/models/4201/realistic-vision-v51"
      
    - name: "deliberate_v3.safetensors"
      type: "checkpoint"
      description: "Deliberate v3 - Artistic and creative portraits"
      source: "civitai"
      url: "https://civitai.com/models/4823/deliberate"
      
    - name: "dreamshaper_v8.safetensors"
      type: "checkpoint"
      description: "DreamShaper v8 - Dreamy and artistic style"
      source: "civitai"
      url: "https://civitai.com/models/128713/dreamshaper"

# ControlNet models
controlnet:
  models:
    - name: "softedge_sdxl_dexined.safetensors"
      type: "controlnet"
      description: "SoftEdge SDXL Dexined - Soft edge detection for portraits"
      source: "civitai"
      url: "https://civitai.com/models/101055/softedge-sdxl-dexined"
      
    - name: "canny_sdxl.safetensors"
      type: "controlnet"
      description: "Canny SDXL - Edge detection for structure control"
      source: "civitai"
      url: "https://civitai.com/models/101055/canny-sdxl"
      
    - name: "lineart_sdxl.safetensors"
      type: "controlnet"
      description: "LineArt SDXL - Line art detection for clean edges"
      source: "civitai"
      url: "https://civitai.com/models/101055/lineart-sdxl"

# ADetailer models
adetailer:
  models:
    - name: "face_yolov8n.pt"
      type: "detection"
      description: "YOLOv8n face detection model"
      source: "github"
      url: "https://github.com/Bing-su/adetailer"
      
    - name: "face_yolov8s.pt"
      type: "detection"
      description: "YOLOv8s face detection model (more accurate)"
      source: "github"
      url: "https://github.com/Bing-su/adetailer"

# Model download settings
download:
  civitai_api_key: ""  # Set your CivitAI API key here
  timeout: 1800        # 30 minutes
  retry_attempts: 3
  chunk_size: 1048576  # 1MB chunks
  
# Model paths
paths:
  stable_diffusion: "models/Stable-diffusion"
  controlnet: "models/ControlNet"
  adetailer: "models/adetailer"
  lora: "models/Lora"
  embeddings: "models/embeddings"
