# Crisp Lines preset
general:
  backend: "a1111"
  a1111_endpoint: "http://127.0.0.1:7860"

b_pass:
  denoise: 0.18
  cfg: 4.3
  steps: 31
  sampler: "DPM++ SDE Karras"
  mask_blur_px: 12

  use_controlnet: true
  controlnet_module: "softedge_hed"
  controlnet_model: "controlnet-sd-xl-1.0-softedge-dexined.safetensors"
  controlnet_weight: 0.58
  controlnet_guidance_start: 0.00
  controlnet_guidance_end: 0.60
  controlnet_mode: 1

  use_controlnet2: true
  controlnet2_module: "canny"
  controlnet2_model: "controlnet-sd-xl-1.0-canny.safetensors"
  controlnet2_weight: 0.52
  controlnet2_guidance_start: 0.25
  controlnet2_guidance_end: 0.90
  controlnet2_mode: 2

  use_adetailer: true
  ad_model: "face_yolov8n.pt"
  ad_confidence: 0.33
  ad_mask_min_ratio: 0.01
  ad_dilate_erode: 16
  ad_mask_blur: 14
  ad_denoise: 0.16
